menu:
# - {name: 'people', url: '/people'}
- {name: 'publications', url: '/publications'}
- {name: 'presentations', url: '/presentations'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

# presentations:
# - {name: 'Attractiveness and competitiveness … but for who? Regional place marketing collaboration from a discursive perspective, Lectio praecursoria, Joensuu, Finland, 04.12.2020', url: 'lectio-praecursoria'}
# - {name: 'Vetovoimaa ja kilpailukykyä, mutta kenelle? - Maakunnallinen aluemarkkinointiyhteistyö diskursiivisesta näkökulmasta. Maantieteenpäivät, Vaasa, Finland, 24.10.2019 - 25.10.2019.', url: ''}
# - {name: 'Discourse and power: Case study of discursive construction of stakeholders positions inregional place marketing collaboration. 5th Corfu Symposium on Managing and Marketing places. Korfu, Greece, 18.04.2018.', url: ''}
# - {name: 'Discursive construction issues and interest by stakeholders in two regional level place marketing projects in Eastern Finland. Inaugural Conference of the International Place Branding Association, 8.12.2016. Lontoo, Great Britain (UK), 08.12.2016.', url: ''}
# - {name: 'Discursive legitimation in regional level place branding. 5th International Colloquium on Place Brand Management. Cogne, Italy, 03.09.2015.', url: ''}
# - {name: 'Maakunnallisen aluebrändäämisen diskursiivinen legitimaatio. Hallinnon tutkimuksen päivät. Vaasa, Finland, 27.11.2014.', url: ''}
# - {name: 'Stakeholder participation in place branding: a case study of three regional level place branding programs in Finland. Integrated Territorial Management and Governance - III Postgraduate workshop of the ESPON/ENECON project. Aalborg, Denmark, 28.03.2014.', url: ''}
# - {name: 'Stellar Structures', url: 'stellar-structures'}

# people:
# - {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
# - {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
# - {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

# Presentations:
# - {name: 'Vetovoimaa ja kilpailukykyä, mutta kenelle? - Maakunnallinen aluemarkkinointiyhteistyö diskursiivisesta näkökulmasta. Maantieteenpäivät, Vaasa, Finland, 24.10.2019 - 25.10.2019.'}
# - {name: 'Discourse and power: Case study of discursive construction of stakeholders positions inregional place marketing collaboration. 5th Corfu Symposium on Managing and Marketing places. Korfu, Greece, 18.04.2018.'}
# - {name: 'Discursive construction issues and interest by stakeholders in two regional level place marketing projects in Eastern Finland. Inaugural Conference of the International Place Branding Association, 8.12.2016. Lontoo, Great Britain (UK), 08.12.2016.'}
# - {name: 'Discursive legitimation in regional level place branding. 5th International Colloquium on Place Brand Management. Cogne, Italy, 03.09.2015.'}
# - {name: 'Maakunnallisen aluebrändäämisen diskursiivinen legitimaatio. Hallinnon tutkimuksen päivät. Vaasa, Finland, 27.11.2014.'}
# - {name: 'Stakeholder participation in place branding: a case study of three regional level place branding programs in Finland. Integrated Territorial Management and Governance - III Postgraduate workshop of the ESPON/ENECON project. Aalborg, Denmark, 28.03.2014.'}
# - {name: 'Stellar Structures', url: 'stellar-structures'}

social:
# - {icon: 'github', link: 'https://github.com/LeNPaul'}
- {icon: 'twitter', link: 'https://twitter.com/juha_m_halme'}
# - {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/juha-halme-a030324a'}
- {icon: 'university', link: 'https://uefconnect.uef.fi/en/person/juha.halme/'}

contacts:
- {name: 'Dr. Juha Halme', title: 'Project Researcher', department: 'Karelian Institute', phone: '+358 50 570 3754', office: 'Aurora building office 1188', institution: 'University of Eastern Finland', institution_address: 'Yliopistokatu 2, 80100 Joensuu', email: 'juha.halme@uef.fi', image: 'assets/img/contact.jpg'}
